//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFTPGetConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_importSFTP
    {
        public int PK { get; set; }
        public string FolderName { get; set; }
        public string gImportID { get; set; }
        public string workingDir { get; set; }
        public string pgm { get; set; }
        public string arguments { get; set; }
        public string downFileFull { get; set; }
        public string filePath { get; set; }
        public string ftpServer { get; set; }
        public string ftpUser { get; set; }
        public string ftpPass { get; set; }
        public string ftpSrcDir { get; set; }
        public string ftpSrcArchive { get; set; }
        public Nullable<bool> deleteAfterDownload { get; set; }
        public Nullable<bool> passive { get; set; }
        public int FK_downloadType { get; set; }
        public string importID { get; set; }
        public Nullable<bool> reqTracking { get; set; }
        public Nullable<int> importOrder { get; set; }
        public Nullable<bool> autoDownload { get; set; }
        public Nullable<bool> appendTimestamp { get; set; }
    }
}
